### ISSUE TITLE
Polymer-based documentation/demo site not being correctly created

### ISSUE THREAD

**Issue by azinck** [elmsln/wcfactory#250]
When I create a new element (wcf element) I end up with an instruction to run yarn start in the new element's directory.  I understand that this is meant to generate some documentation and a demo page for the new element using Polymer.  This is what my page ends up looking like:
![image](https://user-images.githubusercontent.com/1158159/49594963-fea33000-f944-11e8-80af-3da1cc1bd550.png)

It's totally blank despite the fact that I've defined a couple of properties for my element.  I assume the problem comes down to polymer analyze not doing the right thing somehow.  My analysis.json file is basically empty:
```
{
  "schema_version": "1.0.0"
}

```

For reference, here are the contents of my properties file:
```
{
  "text": {
    "name": "text",
    "type": "String",
    "value": "",
    "reflectToAttribute": false,
    "observer": false
  },
  "img": {
    "name": "img",
    "type": "String",
    "value": "",
    "reflectToAttribute": false,
    "observer": false
  }
}
```

Also: I'm not sure if it's related, but when I generate an element I do get this warning: 
```
warning Lockfile has incorrect entry for "@lrnwebcomponents/hax-body-behaviors@^0.0.0". Ignoring it.
Couldn't find any versions for "@lrnwebcomponents/hax-body-behaviors" that matches "^0.0.0"
? Please choose a version of "@lrnwebcomponents/hax-body-behaviors" from this list: (Use arrow keys)
```

I'm not sure what's causing the 0.0.0 to be written to the yarn lock file, but I pick 0.0.38 as the version of hax-body-behaviors and it seems to complete happily.

*Edit:* I should mention that I get exactly the same results for all element types I've tried.  I've tested with vanilla JS, SkateJS, and Polymer elements.

**Comment by btopro** [comment]
pull the latest version of wcfactory it should resolve the 0.0.0 issue w/ new elements.

Would you mind updating the tooling `yarn global add @wcfactory/cli` and then trying again and see if there's an issue. If there is could you post the code to a repo so I can pull it down and look at it a bit?

Another way to try and get at the error is to try running `yarn run build` or if that fails, `polymer build` which should then show an error message which should help us track it down

**Comment by azinck** [comment]
Thank you for your quick response! Unfortunately I'm having no luck with these suggestions. 

When you say "pull the latest version of wcfactory" I'm assuming you mean run `yarn global add @wcfactory/cli`?  I did that, and attempted creating a new element but ran into all the same problems.

I wondered if all my existing .lock files were confusing the situation, so I deleted my entire wcfactory "company" directory and started from scratch creating a company, factory, and element.  Unfortunately I got all the same exact behavior (including the problem with 0.0.0 in the lock file).

When you suggest that I run `yarn run build` can you clarify where you want me to run that from? I ran it from my factory directory and this is what I got:

```
➜  wcfactory-test git:(master) ✗ yarn run build
yarn run v1.12.3
$ lerna run build --no-bail
lerna notice cli v3.5.1
lerna info Executing command in 1 package: "yarn run build"
lerna info run Ran npm script 'build' in '@azinck/popup-info' in 19.2s:
$ ../../node_modules/.bin/gulp && ../../node_modules/.bin/rollup -c && ../../node_modules/.bin/prettier --ignore-path ../../.prettierignore --write '**/*.{js,json}'
[11:53:58] Using gulpfile ~/wcfactory-test/factories/wcfactory-test/elements/popup-info/gulpfile.js
[11:53:58] Starting 'default'...
[11:53:58] Starting 'merge'...
[11:53:58] Finished 'merge' after 55 ms
[11:53:58] Starting 'analyze'...
[11:54:02] Finished 'analyze' after 3.67 s
[11:54:02] Starting 'build'...
[11:54:13] Finished 'build' after 12 s
[11:54:13] Starting 'compile'...
child process exited with code 0
[11:54:13] Finished 'compile' after 19 ms
[11:54:13] Starting 'sourcemaps'...
[11:54:13] Finished 'sourcemaps' after 4.56 ms
[11:54:13] Finished 'default' after 15 s
analysis.json 40ms
gulpfile.js 59ms
polymer.json 19ms
popup-info.js 49ms
popup-info.story.js 29ms
rollup.config.js 8ms
src/popup-info-hax.json 9ms
src/popup-info-properties.json 12ms
src/popup-info.js 26ms
lerna success run Ran npm script 'build' in 1 package in 19.2s:
lerna success - @azinck/popup-info
✨  Done in 19.97s.
```

`polymer build` doesn't do anything since I don't have polymer installed:
```
➜  wcfactory-test git:(master) ✗ polymer build
zsh: command not found: polymer
```

Here's my code on a repo: https://github.com/azinck/wcfactory-test

**Comment by btopro** [comment]
so the `polymer build` and `yarn run build` commands from inside `elements/popup-info` should at least run (that's the location I meant).

Try this as well (this is something we're working on the difference between flexibility and annoyance).

Go to your company directory and see the `templates` directory (you should also see a builds, factories, and storybooks directory at this level) and either run `wcf start` again from this directory (the company level) or overwrite the files in `templates` with those found here -- https://github.com/elmsln/wcfactory/tree/master/packages/generator-wcfactory/generators/start/templates/templates

**Comment by btopro** [comment]
These dictate the starting points for your new elements and they've been updated since. The "flexibility vs annoyance" is that you can actually override these definitions to kick out your own elements or modify our structures. Once we get them perfect for working with then this will be lessa an issue but maybe a "refresh templates" script is in order...

**Comment by azinck** [comment]
Here's the result of `yarn run build` in the directory for my specific element:
```
➜  popup-info git:(master) ✗ yarn run build
yarn run v1.12.3
$ ../../node_modules/.bin/gulp && ../../node_modules/.bin/rollup -c && ../../node_modules/.bin/prettier --ignore-path ../../.prettierignore --write '**/*.{js,json}'
[13:29:32] Using gulpfile ~/wcfactory-test/factories/wcfactory-test/elements/popup-info/gulpfile.js
[13:29:32] Starting 'default'...
[13:29:32] Starting 'merge'...
[13:29:32] Finished 'merge' after 37 ms
[13:29:32] Starting 'analyze'...
[13:29:35] Finished 'analyze' after 3.48 s
[13:29:35] Starting 'build'...
[13:29:46] Finished 'build' after 11 s
[13:29:46] Starting 'compile'...
child process exited with code 0
[13:29:46] Finished 'compile' after 36 ms
[13:29:46] Starting 'sourcemaps'...
[13:29:46] Finished 'sourcemaps' after 8.91 ms
[13:29:46] Finished 'default' after 14 s

popup-info.umd.js → popup-info.umd.js...
(!) Unresolved dependencies
https://rollupjs.org/guide/en#warning-treating-module-as-external-dependency
@lrnwebcomponents/hax-body-behaviors/lib/HAXWiring.js (imported by popup-info.umd.js)
(!) Missing global variable name
Use output.globals to specify browser global variable names corresponding to external modules
@lrnwebcomponents/hax-body-behaviors/lib/HAXWiring.js (guessing 'HAXWiring_js')
created popup-info.umd.js in 1.5s
analysis.json 45ms
gulpfile.js 73ms
polymer.json 21ms
popup-info.js 45ms
popup-info.story.js 26ms
rollup.config.js 9ms
src/popup-info-hax.json 28ms
src/popup-info-properties.json 12ms
src/popup-info.js 25ms
✨  Done in 17.72s.

```

`polymer build` still doesn't work:
```
➜  popup-info git:(master) ✗ polymer build 
zsh: command not found: polymer
```

As for the updates for your templates: that should not be an issue.  After your advice to update wcfactory I completely destroyed my entire company directory and started from scratch (creating new company directory, running wcf start, wcf factory, wcf element, etc.).

**Comment by btopro** [comment]
gotcha. So it looks like it built then, is it still not able to be worked on?

**Comment by btopro** [comment]
cheating on the demo site can be done via `http://127.0.0.1:8081/components/@lrnwebcomponents/outline-designer/demo/` like I have currently, if you just add /demo to the url that pops up after the name of your org/element.

Not a total solution but trying to help hunt down workflow issue

**Comment by azinck** [comment]
Ok, if I go to the /demo url I do get the demo.  But the regular documentation url continues to look exactly how it looks in my original post on this issue.  And the analysis.json file is still essentially empty, exactly like my original post.

**Comment by btopro** [comment]
yeah I'll see if I can replicate that now; I have had that happen before at times.

**Comment by btopro** [comment]
![2018-12-06_13-44-53](https://user-images.githubusercontent.com/329735/49604906-23a39d00-f95d-11e8-8b7e-a3d047a902fb.png)
🤷‍♂️

**Comment by btopro** [comment]
can you tell me if your element's node_modules directory is a symlink or if it's a real folder?

Also might want to try `yarn global add polymer-cli` and see if that helps at all

**Comment by azinck** [comment]
It's a symlink:
```
➜  popup-info git:(master) ✗ ls -al
total 216
drwxr-xr-x  26 azinck  staff    832 Dec  6 13:29 .
drwxr-xr-x   5 azinck  staff    160 Dec  6 12:00 ..
-rw-r--r--   1 azinck  staff   6148 Dec  6 11:49 .DS_Store
-rw-r--r--   1 azinck  staff    346 Dec  6 12:00 .editorconfig
-rw-r--r--   1 azinck  staff     32 Dec  6 12:00 .gitignore
-rw-r--r--   1 azinck  staff     13 Dec  6 12:00 .npmignore
-rw-r--r--   1 azinck  staff     15 Dec  6 12:00 .surgeignore
-rw-r--r--   1 azinck  staff    305 Dec  6 12:00 .travis.yml
-rw-r--r--   1 azinck  staff  11317 Dec  6 12:00 LICENSE.md
-rw-r--r--   1 azinck  staff   2209 Dec  6 12:00 README.md
-rw-r--r--   1 azinck  staff     32 Dec  6 13:40 analysis.json
drwxr-xr-x   3 azinck  staff     96 Dec  6 12:00 demo
-rw-r--r--   1 azinck  staff   4107 Dec  6 12:00 gulpfile.js
-rw-r--r--   1 azinck  staff    480 Dec  6 12:00 index.html
lrwxr-xr-x   1 azinck  staff     18 Dec  6 11:50 node_modules -> ../../node_modules
-rw-r--r--   1 azinck  staff   2016 Dec  6 12:00 package.json
-rw-r--r--   1 azinck  staff    955 Dec  6 12:00 polymer.json
-rw-r--r--   1 azinck  staff   3554 Dec  6 13:29 popup-info.amd.js
-rw-r--r--   1 azinck  staff   2229 Dec  6 13:29 popup-info.es6.js
-rw-r--r--   1 azinck  staff   4164 Dec  6 12:00 popup-info.js
-rw-r--r--   1 azinck  staff   1821 Dec  6 12:00 popup-info.story.js
-rw-r--r--   1 azinck  staff   4738 Dec  6 13:29 popup-info.umd.js
-rw-r--r--   1 azinck  staff   6279 Dec  6 13:29 popup-info.umd.js.map
-rw-r--r--   1 azinck  staff    184 Dec  6 12:00 rollup.config.js
drwxr-xr-x   7 azinck  staff    224 Dec  6 13:40 src
drwxr-xr-x   4 azinck  staff    128 Dec  6 12:00 test

```

I ran `yarn global add polymer-cli` followed by `yarn start` and ended up with the exact same problem.

Running `polymer build` now does work of course.  It gives us another clue:
```
➜  popup-info git:(master) ✗ polymer build
info:	Clearing build/ directory...
info:	(es6) Building...
info:	(es5-amd) Building...


window.customElements.define(PopupInfo.tag, PopupInfo);
                             ~~~~~~~~~~~~~

file:///Users/azinck/wcfactory-test/factories/wcfactory-test/elements/popup-info/popup-info.js(197,30) warning [cant-determine-element-tagname] - Unable to evaluate this expression down to a definitive string tagname.
info:	(es6) Build complete!
info:	(es5-amd) Build complete!
```

**Comment by btopro** [comment]
your welcome to try setting that to 'popup-info' and see if that helps that line. IDEs complain about that but it seems to work still / have seen it elsewhere (happy to change the tooling if this fixes it tho)

**Comment by azinck** [comment]
Do you mean I should literally just change the name of the class?

**Comment by btopro** [comment]
`window.customElements.define(PopupInfo.tag, PopupInfo);`
to
`window.customElements.define('popup-info', PopupInfo);`

**Comment by azinck** [comment]
That change makes `polymer build` happy:

```
➜  popup-info git:(master) ✗ polymer build
info:	Clearing build/ directory...
info:	(es6) Building...
info:	(es5-amd) Building...
info:	(es6) Build complete!
info:	(es5-amd) Build complete!
```

But running `yarn start` still results in the documentation page looking exactly like my original screenshot, and the analysis.json file is still empty (save for the schema_version entry).

**Comment by btopro** [comment]
what happens if you type `polymer analyze --input demo/index.html > analysis.json`

**Comment by btopro** [comment]
or `polymer analyze --input popup-info.js > analysis.json`

**Comment by azinck** [comment]
Both run successfully without returning returning any messages.   My analysis.json remains unchanged.

If I run it without writing the output to analysis.json I get this (as you would expect):
```
➜  popup-info git:(master) ✗ polymer analyze --input popup-info.js
{
  "schema_version": "1.0.0"
}
```

**Comment by btopro** [comment]
can you paste popup-info.js here?

**Comment by azinck** [comment]
It's here: https://github.com/azinck/wcfactory-test/blob/master/elements/popup-info/popup-info.js

**Comment by btopro** [comment]
ahhh, a vanilla element.

try removing
```
  reflectToAttribute: false,
  observer: false
```
stuff from the properties area. That's a very polymer specific thing and I think the tooling will goof stuff up when we claim to not observe (when really it just shouldn't be set if false)

**Comment by btopro** [comment]
weird. maybe it's that it's a vanilla element though I have been able to analyze those in the past. Maybe work w/ the tooling a bit to make an element and then once it's a real element if this is still going on it might be something to bring to the polymer CLI issue queue (even just posting and referncing this and the element in question to say "something odd is here")

**Comment by azinck** [comment]
FWIW, I just tried this with a Polymer version of the element and am having the same problem (I again had to switch the window.customElements.define call to use the explicit string in order to get `polymer build` to complete cleanly).

Whatever I do I can't seem to get polymer analyze to work properly for me.

Thanks for your assistance.  I'll try to get some of the JS experts around here to take a closer look at this with me.

**Comment by btopro** [comment]
ya not sure what would be causing that if it can't resolve the imports or what the gig is there; maybe even some kind of file system level difference if your using a newer OSX relative to me or something. The analyze command should run pretty uniformly; we've got 170+ elements now that kick out and the vast majority of them have that site working (now and then it won't, the docs part that is, and so I usually just keep working on it comes back eventually)

**Comment by btopro** [comment]
@azinck is this on a windows or mac or linux? I've noticed some goofiness w/ PC when it comes to build.

**Comment by azinck** [comment]
This is on a Mac.

**Comment by btopro** [comment]
hmm ok. I'll leave this open even though I can't track down when this happens

**Comment by azinck** [comment]
Thanks -- did you try using my repo?

**Comment by btopro** [comment]
yup, just generated it now
![2018-12-11_11-06-50](https://user-images.githubusercontent.com/329735/49813199-efe9be00-fd34-11e8-84f9-b2ae6419e3de.png)

**Comment by azinck** [comment]
Mysterious.  Thanks for taking a look at it, though.

**Comment by btopro** [comment]
`polymer --version` I have 1.8.1 how bout you?

**Comment by azinck** [comment]
1.9.1

**Comment by btopro** [comment]
https://github.com/Polymer/tools/issues/361#issuecomment-431326335 could offer clues. try renaming your factory to not have the word -test in it (wow that sounds stupid...) also if that doesn't work see if stating the input file to analyze helps at all.

**Comment by azinck** [comment]
Wow.  I shudder to think of what might be going on inside polymer analyze because I tried it in a factory that doesn't end in -test and, lo-and-behold, it works!

**Comment by btopro** [comment]
ugh; well that's good :)
